# Generated by Django 4.2.6 on 2023-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreport',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
