# Generated by Django 4.2.6 on 2023-10-14 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0002_alter_marketreport_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreport',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
