# Generated by Django 4.2.6 on 2023-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0003_alter_marketreport_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreport',
            name='published',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
