# Generated by Django 4.2.6 on 2023-10-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0005_alter_marketreport_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketreport',
            name='likelihood',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
